language: java
jdk: oraclejdk8

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dvaadin.testbench.developer.license=$TESTBENCH_LICENSE -Dvaadin.charts.developer.license=$CHARTS_LICENSE

# Cache requires a master build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2

before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/orders
