language: java
jdk: openjdk8
dist: xenial
sudo: true

# Make it possible to run tests on a local Chrome
before_install:
# The Following line fixes random Chrome startup failures (https://github.com/SeleniumHQ/docker-selenium/issues/87)
 - export DBUS_SESSION_BUS_ADDRESS=/dev/null

addons:
  chrome: stable

before_install: ./.travis.before_install.sh
script: ./.travis.script.sh

deploy:
  - provider: script
    script: ./.travis.deploy.sh
    skip_cleanup: true
    on:
      branch: master

# Cache requires a master build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2

before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/starter/bakery
