package com.vaadin.template.orders.ui.view.orders;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.testbench.elements.ButtonElement;
import com.vaadin.testbench.elements.GridLayoutElement;
import com.vaadin.testbench.elements.VerticalLayoutElement;
import com.vaadin.testbench.elementsbase.ServerClass;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 */
@ServerClass("com.vaadin.template.orders.ui.view.orders.OrderHistoryDesign")
@AutoGenerated
public class OrderHistoryDesignElement extends VerticalLayoutElement {

	public GridLayoutElement getItems() {
		return $(com.vaadin.testbench.elements.GridLayoutElement.class).id(
				"items");
	}

	public ButtonElement getAddComment() {
		return $(com.vaadin.testbench.elements.ButtonElement.class).id(
				"addComment");
	}
}