package com.vaadin.template.orders.ui.view.orders;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.testbench.elements.AbsoluteLayoutElement;
import com.vaadin.testbench.elements.ButtonElement;
import com.vaadin.testbench.elements.GridElement;
import com.vaadin.testbench.elementsbase.ServerClass;

/**
 * !! DO NOT EDIT THIS FILE !!
 *
 * This class is generated by Vaadin Designer and will be overwritten.
 */
@ServerClass("com.vaadin.template.orders.ui.view.orders.OrdersListViewDesign")
@AutoGenerated
public class OrdersListViewDesignElement extends AbsoluteLayoutElement {

	public ButtonElement getNewOrder() {
		return $(com.vaadin.testbench.elements.ButtonElement.class).id("newOrder");
	}

	public GridElement getList() {
		return $(com.vaadin.testbench.elements.GridElement.class).id("list");
	}
}