package com.vaadin.template.orders.ui.view.orders;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.testbench.elements.CssLayoutElement;
import com.vaadin.testbench.elements.VerticalLayoutElement;
import com.vaadin.testbench.elementsbase.ServerClass;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 */
@ServerClass("com.vaadin.template.orders.ui.view.orders.OrderHistoryDesign")
@AutoGenerated
public class OrderHistoryDesignElement extends VerticalLayoutElement {

	public CssLayoutElement getItems() {
		return $(com.vaadin.testbench.elements.CssLayoutElement.class).id("items");
	}

}