package com.vaadin.template.orders.ui.view.orders;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.testbench.elements.ButtonElement;
import com.vaadin.testbench.elements.ComboBoxElement;
import com.vaadin.testbench.elements.CssLayoutElement;
import com.vaadin.testbench.elements.DateFieldElement;
import com.vaadin.testbench.elements.HorizontalLayoutElement;
import com.vaadin.testbench.elements.LabelElement;
import com.vaadin.testbench.elements.TextFieldElement;
import com.vaadin.testbench.elements.VerticalLayoutElement;
import com.vaadin.testbench.elementsbase.ServerClass;

/**
 * !! DO NOT EDIT THIS FILE !!
 *
 * This class is generated by Vaadin Designer and will be overwritten.
 */
@ServerClass("com.vaadin.template.orders.ui.view.orders.OrderEditViewDesign")
@AutoGenerated
public class OrderEditViewDesignElement extends VerticalLayoutElement {

	public HorizontalLayoutElement getReportHeader() {
		return $(com.vaadin.testbench.elements.HorizontalLayoutElement.class).id("reportHeader");
	}

	public LabelElement getOrderId() {
		return $(com.vaadin.testbench.elements.LabelElement.class).id("orderId");
	}

	public LabelElement getOrderState() {
		return $(com.vaadin.testbench.elements.LabelElement.class).id("orderState");
	}

	public ButtonElement getSetState() {
		return $(com.vaadin.testbench.elements.ButtonElement.class).id("setState");
	}

	public DateFieldElement getDueDate() {
		return $(DateFieldElement.class).id("dueDate");
	}

	public ComboBoxElement getDueTime() {
		return $(ComboBoxElement.class).id("dueTime");
	}

	public ComboBoxElement getPickupLocation() {
		return $(ComboBoxElement.class).id("pickupLocation");
	}

	public TextFieldElement getFullName() {
		return $(com.vaadin.testbench.elements.TextFieldElement.class).id("fullName");
	}

	public TextFieldElement getPhone() {
		return $(com.vaadin.testbench.elements.TextFieldElement.class).id("phone");
	}

	public TextFieldElement getDetails() {
		return $(com.vaadin.testbench.elements.TextFieldElement.class).id("details");
	}

	public CssLayoutElement getProductInfoContainer() {
		return $(com.vaadin.testbench.elements.CssLayoutElement.class).id("productInfoContainer");
	}

	public ButtonElement getAddItems() {
		return $(com.vaadin.testbench.elements.ButtonElement.class).id("addItems");
	}

	public LabelElement getTotal() {
		return $(com.vaadin.testbench.elements.LabelElement.class).id("total");
	}

	public OrderHistoryElement getHistory() {
		return $(com.vaadin.template.orders.ui.view.orders.OrderHistoryElement.class).id("history");
	}

	public ButtonElement getEditOrCancel() {
		return $(com.vaadin.testbench.elements.ButtonElement.class).id("cancel");
	}

	public ButtonElement getOk() {
		return $(com.vaadin.testbench.elements.ButtonElement.class).id("ok");
	}
}