package com.vaadin.template.orders.ui.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.testbench.elements.VerticalLayoutElement;
import com.vaadin.testbench.elementsbase.ServerClass;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 */
@ServerClass("com.vaadin.template.orders.ui.view.AccessDeniedDesign")
@AutoGenerated
public class AccessDeniedDesignElement extends VerticalLayoutElement {
}