package com.vaadin.starter.bakery.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.starter.bakery.ui.view.MenuElement;
import com.vaadin.testbench.elements.ButtonElement;
import com.vaadin.testbench.elements.HorizontalLayoutElement;
import com.vaadin.testbench.elements.VerticalLayoutElement;
import com.vaadin.testbench.elementsbase.ServerClass;

/**
 * !! DO NOT EDIT THIS FILE !!
 *
 * This class is generated by Vaadin Designer and will be overwritten.
 */
@ServerClass("com.vaadin.starter.bakery.ui.MainViewDesign")
@AutoGenerated
public class MainViewDesignElement extends HorizontalLayoutElement {

	public ButtonElement getMenuButton() {
		return $(com.vaadin.testbench.elements.ButtonElement.class).id("menuButton");
	}

	public MenuElement getMenu() {
		return $(MenuElement.class).id("menu");
	}

	public ButtonElement getStorefront() {
		return $(com.vaadin.testbench.elements.ButtonElement.class).id("storefront");
	}

	public ButtonElement getDashboard() {
		return $(com.vaadin.testbench.elements.ButtonElement.class).id("dashboard");
	}

	public ButtonElement getUsers() {
		return $(com.vaadin.testbench.elements.ButtonElement.class).id("users");
	}

	public ButtonElement getProducts() {
		return $(com.vaadin.testbench.elements.ButtonElement.class).id("products");
	}

	public ButtonElement getLogout() {
		return $(com.vaadin.testbench.elements.ButtonElement.class).id("logout");
	}

	public VerticalLayoutElement getContent() {
		return $(com.vaadin.testbench.elements.VerticalLayoutElement.class).id("content");
	}
}