package com.vaadin.template.orders.ui.view.orders;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.annotations.PropertyId;
import com.vaadin.template.orders.ui.components.PickupLocationComboBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.DateTimeField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class OrderEditViewDesign extends VerticalLayout {
	protected HorizontalLayout reportHeader;
	protected Label orderId;
	protected Label state;
	protected Button setState;
	protected DateTimeField dueDateTime;
	protected PickupLocationComboBox pickupLocation;
	@PropertyId("customer.firstName")
	protected TextField firstName;
	@PropertyId("customer.lastName")
	protected TextField lastName;
	@PropertyId("customer.phoneNumber")
	protected TextField phone;
	@PropertyId("customer.email")
	protected TextField email;
	@PropertyId("customer.details")
	protected TextField details;
	protected CssLayout productInfoContainer;
	protected Button addItems;
	protected Label total;
	protected OrderHistory history;
	protected Button editBackCancel;
	protected Button ok;

	public OrderEditViewDesign() {
		Design.read(this);
	}
}
