package com.vaadin.template.orders

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class Barista extends Simulation {

  val baseUrl = "http://localhost:8080"
  
	val httpProtocol = http
		.baseURL(baseUrl)
		.acceptHeader("*/*")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("en-US,en;q=0.5")
		.userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0")

	val headers_0 = Map(
		"Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
		"Upgrade-Insecure-Requests" -> "1")
	val headers_4 = Map("Accept" -> "text/css,*/*;q=0.1")
	val headers_6 = Map("Content-Type" -> "application/json; charset=UTF-8")
	val headers_7 = Map("Pragma" -> "no-cache")

  val initSyncAndClientIds = exec((session) => {
    session.setAll(
      "syncId" -> 0,
      "clientId" -> 0
      )})

  val syncIdExtract = regex("""syncId": ([0-9]*),""").saveAs("syncId")
  val clientIdExtract = regex("""clientId": ([0-9]*),""").saveAs("clientId")
  val xsrfTokenExtract = regex("""Vaadin-Security-Key\\":\\"([^\\]+)""").saveAs("seckey")
  
	val scn = scenario("Barista")
		.exec(http("request_0")
			.get("/")
			.headers(headers_0))
		.pause(10)
    .exec(initSyncAndClientIds)
		.exec(http("request_1")
			.post("/login")
			.headers(headers_0)
			.formParam("username", "barista@vaadin.com")
			.formParam("password", "barista"))
		.exec(http("request_5")
			.post("/?v-1495614595285")
			.formParam("v-browserDetails", "1")
			.formParam("theme", "orderstheme")
			.formParam("v-appId", "ROOT-2521314")
			.formParam("v-sh", "1692")
			.formParam("v-sw", "3008")
			.formParam("v-cw", "1254")
			.formParam("v-ch", "824")
			.formParam("v-curdate", "1495614595285")
			.formParam("v-tzo", "-180")
			.formParam("v-dstd", "60")
			.formParam("v-rtzo", "-120")
			.formParam("v-dston", "true")
			.formParam("v-vw", "1254")
			.formParam("v-vh", "0")
			.formParam("v-loc", "http://localhost:8080/")
			.formParam("v-wn", "ROOT-2521314-0.6857735007173337")
    .check(xsrfTokenExtract))
		.pause(1)
		.exec(http("request_6")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_6)
      .check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("Barista_0006_request.txt")))
		.pause(10)
		.exec(http("request_9")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_6)
      .check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("Barista_0009_request.txt")))
		.pause(3)
		.exec(http("request_10")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_6)
      .check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("Barista_0010_request.txt")))
		.pause(1)
		.exec(http("request_11")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_6)
      .check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("Barista_0011_request.txt")))
		.pause(1)
		.exec(http("request_12")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_6)
      .check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("Barista_0012_request.txt")))
		.pause(2)
		.exec(http("request_13")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_6)
      .check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("Barista_0013_request.txt")))
		.pause(5)
		.exec(http("request_14")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_6)
      .check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("Barista_0014_request.txt")))
		.pause(3)
		.exec(http("request_15")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_6)
      .check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("Barista_0015_request.txt")))
		.pause(2)
		.exec(http("request_16")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_6)
      .check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("Barista_0016_request.txt")))
		.pause(10)
		.exec(http("request_17")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_6)
      .check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("Barista_0017_request.txt")))
		.pause(10)
		.exec(http("request_18")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_6)
      .check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("Barista_0018_request.txt")))
		.pause(15)
		.exec(http("request_19")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_6)
      .check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("Barista_0019_request.txt")))

	setUp(scn.inject( rampUsers(1) over (1 seconds)) ).protocols(httpProtocol)
}