package com.vaadin.starter.bakery.ui.view.dashboard;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.testbench.elements.AbstractComponentElement;
import com.vaadin.testbench.elements.VerticalLayoutElement;
import com.vaadin.testbench.elementsbase.ServerClass;

/**
 * !! DO NOT EDIT THIS FILE !!
 *
 * This class is generated by Vaadin Designer and will be overwritten.
 */
@ServerClass("com.vaadin.starter.bakery.ui.view.dashboard.DashboardViewDesign")
@AutoGenerated
public class DashboardViewDesignElement extends VerticalLayoutElement {

	public AbstractComponentElement getBoard() {
		return $(com.vaadin.testbench.elements.AbstractComponentElement.class).id("board");
	}
}